---
title: "Analisis exploratorio - tiempos de llegada"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(patchwork)
```

```{r}
remesas <- read_delim("../datos/REMESAS0100012200.txt", delim = "|", skip = 1) %>%
  mutate(timestamp = ymd_hms(paste(ANIO, MES, DIA, HORA, MINUTOS, SEGUNDOS, sep = "-")))
```

La siguiente gráfica muestra que el tiempo de llegada no es independiente
de el porcentaje de votos para cada partido:


```{r}
graficar_acumulados <- function(votos, reordenar = FALSE){
  if(reordenar){
    votos <- votos %>% 
      group_by(timestamp) %>% 
      nest() %>% 
      ungroup() %>% 
      mutate(timestamp = sample(timestamp, length(timestamp))) %>% 
      unnest(cols = data)
  }
  votos_pct <- votos %>% 
    group_by(timestamp, coalición) %>% 
    summarise(num_votos = sum(num_votos), .groups = "drop") %>% 
    group_by(coalición)  %>%
    arrange(timestamp) %>% 
    mutate(acum_votos = cumsum(num_votos)) %>% 
    group_by(timestamp) %>% 
    mutate(total_votos = sum(acum_votos),
         pct_votos = acum_votos / total_votos) 
  graf <- ggplot(votos_pct, aes(x = timestamp, y = pct_votos, group = coalición, colour = coalición)) +
  geom_point()
  graf
}
g_datos <- graficar_acumulados(votos)
g_datos
```
Esto podemos checarlo ordenando al azar y repitiendo la gráfica:

```{r}
grafs_lista <- map(1:5, ~ graficar_acumulados(votos, reordenar = TRUE)) 
grafs_lista[[6]] <- g_datos
wrap_plots(grafs_lista, ncol = 3, guides = "collect")
```

